### ISSUE TITLE
C_BMP180_ONE_U8X constant still present in bmp180_support.c

### ISSUE THREAD

**Issue by jsren** [BoschSensortec/BMP180_driver#3]
Line 324 in `bmp180_support.c` still uses `C_BMP180_ONE_U8X`.

On a personal note, the use of preprocessor definitions *with the number in their name* to replace "evil" numeric literals is ludicrous and near unreadable. In fact the formatting in general throughout `bmp180.c` is unreadable.

**Comment by BoschSensortec** [comment]
Thanks for your feedback. We keep improving our code quality in each release.
