### ISSUE TITLE
bmp180.c freezes at line 341

### ISSUE THREAD

**Issue by Dionakra** [BoschSensortec/BMP180_driver#4]
Hello.

I'm trying to read values from the bmp180 controller with the library and, when I invoke the method bmp180_get_uncomp_temperature(), it freezes at the line 341. In certain occasions, it just doesn't forward and, in other occasions, it throws an error  which says:
CORTEX_M4_0: Trouble reading memory block 0x....

The snippet is:
void main
{
  u16 temp = bmp180_get_uncomp_temperature();
UART_PRINT("%d", temp);
}

Thanks.

**Comment by ma-harvey** [comment]
Are you initializing the library and define the i2c read and write functions and delay function ?

**Comment by BoschSensortec** [comment]
Please refer the support file which gives the details about SPI/I2C read and write functions.
Thank you.
